likecoin/nft-book-press

- pages/nft-book-store/new.vue
- pages/nft-book-store/status/[classId].vue
https://github.com/likecoin/likecoin-api-public/pull/463
> ✨ Support price name and show total stock in new nft book page

- pages/nft-book-store/send/[classId].vue
> 💄 Update send NFT details display

- pages/nft-book-store/index.vue
- pages/nft-book-store/new.vue
- pages/nft-book-store/send/[classId].vue
- pages/nft-book-store/status/[classId].vue
- stores/book-store-api.ts
Requires https://github.com/likecoin/likecoin-api-public/pull/472
> ✨ Add moderator wallet and sales notification email UI

- pages/nft-book-store/new.vue
- pages/nft-book-store/status/[classId].vue
Requires https://github.com/likecoin/likecoin-api-public/pull/473
> ✨ Add name and description bilingual

- pages/nft-book-store/new.vue
> ✏️ Fix wording for listing label

- pages/nft-book-store/new.vue
- pages/nft-book-store/status/[classId].vue
> 🚸 Guard non-empty notification email and moderator wallet fields

- components/QRCode.vue
Closes https://github.com/likecoin/nft-book-press/issues/22
> 👽️ Use new instance of qrCodeStyling for download

- pages/nft-book-store/index.vue
- pages/nft-book-store/send/[classId].vue
- pages/nft-book-store/status/[classId].vue
- stores/nft.ts
Closes https://github.com/likecoin/nft-book-press/issues/25
> ✨ Add NFT class name display

- pages/nft-book-store/new.vue
> [TAS-106] 🚸 Allow delete edition in new listing

- package.json
- pages/nft-book-store/status/[classId].vue
- yarn.lock
Depends on https://github.com/likecoin/likecoin-api-public/pull/505
https://github.com/likecoin/nft-book-press/assets/17264716/ba238b1c-84bb-4b7a-8f8e-524330142514
> [TAS-107] ✨ Add reorder editions UI

- pages/nft-book-store/status/[classId].vue
https://github.com/likecoin/nft-book-press/assets/33746295/9fab5f0f-adf0-4214-ac77-2ebefafbe243
> [TAS-240] ✨ [/status] Allow user manually set to completed

- components/SideNavBar.vue
- package.json
- pages/authz/index.vue
- pages/nft-book-store/new.vue
- pages/nft-book-store/send/[classId].vue
- pages/nft-book-store/status/[classId].vue
- utils/cosmos.ts
- yarn.lock
Base on https://github.com/likecoin/nft-book-press/pull/12
> ✨ Add authz send NFT functions

- pages/nft-book-store/new.vue
- pages/nft-book-store/send/shipping/[classId].vue
- pages/nft-book-store/status/[classId].vue
Requires https://github.com/likecoin/likecoin-api-public/pull/514
> [TAS-317] ✨ Add shipping rate options and handling UI

- pages/nft-book-store/new.vue
https://github.com/likecoin/likecoin-api-public/pull/525
> [TAS-433] ✨ Add default checkout currency setting

- pages/nft-book-store/new.vue
Related: https://github.com/likecoin/likecoin-api-public/pull/532
> [TAS-490] ✨ Allow free price for edition

- pages/nft-book-store/status/[classId].vue
> [TAS-569] 🚸 Sort orders by order date

- app.config.ts
- app.vue
- components/ColorModeButton.vue
- components/QRCode.vue
- components/SideNavBar.vue
- components/SiteHeader.vue
- components/SiteMenu.vue
- components/WalletHeader.vue
- layouts/default.vue
- layouts/page.vue
- nuxt.config.ts
- package.json
- pages/authz/index.vue
- pages/claim-nft-book/[classId].vue
- pages/index.vue
- pages/mint-nft/index.vue
- pages/nft-book-store.vue
- pages/nft-book-store/index.vue
- pages/nft-book-store/new.vue
- pages/nft-book-store/send/[classId].vue
- pages/nft-book-store/send/shipping/[classId].vue
- pages/nft-book-store/status/[classId].vue
- pages/nft-book-store/user/connect/refresh.vue
- pages/nft-book-store/user/connect/return.vue
- pages/nft-book-store/user/index.vue
- stores/ui.ts
- tailwind.config.ts
- utils/cosmos.ts
- utils/index.ts
- yarn.lock
> 💄 Update basic layout with Nuxt UI

- utils/cosmos.ts
seems unused but maybe someone will use it later..
> 🐛 Fix gas price logic

- pages/nft-book-store/new.vue
- pages/nft-book-store/status/[classId].vue
https://github.com/likecoin/likecoin-api-public/pull/556
> [TAS-788] ✨ Add mustClaimToView and hideDownload

- components/PlaceholderCard.vue
- pages/nft-book-store/send/[classId].vue
> [TAS-684] 🐛 Proper handling NFT Id input

- pages/nft-book-store/status/[classId].vue
- pages/nft-book-store/status/[classId]/edit/new.vue
- stores/book-store-api.ts
> [TAS-647] ✨ Add feature for adding edition

- components/NFTClassMetadataLoader.vue
- pages/nft-book-store/index.vue
@WeiJun0827 has updated the API to include pagination (likecoin/likecoin-api-public#574), and as a result, it can display all books in Edmond's PG account (1000+ books).
Also added progress indicator when loading book metadata
> [TAS-896] 👽 Support store list pagination API

- pages/nft-book-store/status/[classId].vue
> [TAS-906] 🚸 Add liker.land link in status page

- pages/mint-nft/index.vue
https://github.com/likecoin/nft-book-press/assets/75730405/46b2f95a-8f92-4e94-b93c-e23de8f8a381
> [TAS-917] 🥅 Guard invalid NFT ID

- components/SiteMenu.vue
- pages/nft-book-store.vue
- pages/nft-book-store/collection/index.vue
- pages/nft-book-store/collection/new.vue
- stores/book-store-api.ts
- stores/collection.ts
- utils/index.ts
Requires: https://github.com/likecoin/likecoin-api-public/pull/578
> [TAS-822] ✨ Add book collection pages

- pages/nft-book-store/collection/status/[collectionId].vue
- pages/nft-book-store/status/[classId].vue
> [TAS-953] ✨ Support showing liker.land purchase link

- constant/index.ts
- pages/nft-book-store/new.vue
- pages/nft-book-store/send/[classId].vue
- pages/nft-book-store/status/[classId]/edit/[editionIndex].vue
- pages/nft-book-store/status/[classId]/edit/new.vue
- utils/cosmos.ts
- utils/index.ts
- Add isAutoDeliver boolean in each price(edition)
- User can set isAutoDeliver when creating an NFT Book or adding a new price
- isAutoDeliver is read-only after created
- Stock of auto delivering price can not be modified
Depends on https://github.com/likecoin/likecoin-api-public/pull/589
> [TAS-880] ✨ Support storing NFT Book in API wallet

- stores/wallet.ts
Requires https://github.com/likecoin/likecoin-api-public/pull/604/files
> 🚸 Extend wallet login token expiration

- pages/nft-book-store/new.vue
- pages/nft-book-store/status/[classId]/edit/[editionIndex].vue
- pages/nft-book-store/status/[classId]/edit/new.vue
- utils/cosmos.ts
Depends on https://github.com/likecoin/likecoin-api-public/pull/612
> [TAS-957] ✨ Support restock and migrate to auto delivery

- pages/mint-nft/index.vue
- pages/nft-book-store/gift/[classId].vue
- pages/nft-book-store/status/[classId].vue
Requires: https://github.com/likecoin/likecoin-api-public/pull/617
> [TAS-962] ✨ Add nft book gift page

- pages/nft-book-store/collection/index.vue
- stores/collection.ts
> ✨ Add viewable collection tab in collection list page

- pages/nft-book-store/collection/status/[collectionId].vue
- pages/nft-book-store/status/[classId].vue
Requires: https://github.com/likecoin/likecoin-api-public/pull/618
TODO: refactor ui and shared function
> [TAS-1093] ✨ Add coupon section in book and collection

- components/NewCouponModal.vue
- pages/nft-book-store/collection/status/[collectionId].vue
- pages/nft-book-store/status/[classId].vue
> [TAS-1177] 💄 Update & refactor new coupon UI

- pages/nft-book-store/status/[classId]/edit/[editionIndex].vue
- pages/nft-book-store/status/[classId]/edit/new.vue
Fixes https://github.com/likecoin/nft-book-press/issues/107
> 🔥 Remove shipping options ui in book edition ui

- pages/nft-book-store/collection/new.vue
- pages/nft-book-store/collection/status/[collectionId]/edit.vue
Requires: https://github.com/likecoin/likecoin-api-public/pull/631
> [TAS-1344] ✨ Add isPhysicalOnly flag for collection

- pages/nft-book-store/collection/status/[collectionId].vue
- pages/nft-book-store/status/[classId].vue
> [TAS-1388] 💄 Reorder status ui component

- pages/nft-book-store/status/[classId].vue
> 🚸 Don't hide shipping page link for any shipping status

- pages/mint-nft/index.vue
Only encountered when iscn_id is set in qs, and deploy mode is static
> 💩 Mitigate iscnIdInput from qs cause button to stuck

- pages/nft-book-store/collection/send/[collectionId].vue
- pages/nft-book-store/collection/send/shipping/[collectionId].vue
- pages/nft-book-store/collection/status/[collectionId].vue
- pages/nft-book-store/send/[classId].vue
- pages/nft-book-store/send/shipping/[classId].vue
- pages/nft-book-store/status/[classId].vue
> 💄 Show readerEmail and buyerEmail instead of just email

- pages/nft-book-store/collection/send/shipping/[collectionId].vue
- pages/nft-book-store/collection/status/[collectionId].vue
- pages/nft-book-store/send/shipping/[classId].vue
- pages/nft-book-store/status/[classId].vue
Requires https://github.com/likecoin/likecoin-api-public/pull/659
> [TAS-1519] ✨ Add buyer phone display

- pages/nft-book-store/user/index.vue
> [TAS-951] 🚸 Add Stripe Connect account description

- constant/network.ts
- nuxt.config.ts
- package.json
- stores/wallet.ts
- yarn.lock
HACK: <UButton> css background color is broken by wallet connect css, re-import tailwind in global.css
> [TAS-1043] ✨ Add @likecoin/wallet-connector

- constant/index.ts
- pages/nft-book-store/collection/new.vue
- pages/nft-book-store/collection/status/[collectionId].vue
- pages/nft-book-store/collection/status/[collectionId]/edit.vue
- pages/nft-book-store/new.vue
- pages/nft-book-store/status/[classId].vue
- pages/nft-book-store/status/[classId]/edit/[editionIndex].vue
- pages/nft-book-store/status/[classId]/edit/new.vue
changes:
- Reorganize fields order, hide low-priority setting to the advance settings.
- Enable setting default currency & DRM in status page 
- The table UI improvements (collection book list)
revamp range:
> [TAS-1461] 🚸 Revamp book listing pages

- constant/index.ts
- pages/auth/redirect.vue
- stores/wallet.ts
Require https://github.com/likecoin/nft-book-press/pull/103
> [TAS-1544] ✨ Add simple authcore support

- components/StripeConnectCard.vue
- constant/index.ts
- nuxt.config.ts
- pages/nft-book-store/collection/new.vue
- pages/nft-book-store/collection/status/[collectionId].vue
- pages/nft-book-store/new.vue
- pages/nft-book-store/status/[classId].vue
- stores/stripe.ts
改動項目：
- Check if the login wallet has a Stripe account and display it under 'Use my account'; if not, prompt to create one
- Check the Stripe account info after entering the wallet.
- Add a save button for this section
> [TAS-950] 🚸 Display current Stripe Account

- pages/nft-book-store/user/index.vue
Base on https://github.com/likecoin/nft-book-press/pull/125
Requires https://github.com/likecoin/likecoin-api-public/pull/651
TODO: sorting, naming the class id, author, etc
> [TAS-1160] ✨ Add commission history in book store user page

- pages/nft-book-store/new.vue
- pages/nft-book-store/status/[classId].vue
Require https://github.com/likecoin/likecoin-api-public/pull/681
> [TAS-1626] 🔧 Add enableCustomMessagePage config for book

- pages/nft-book-store/collection/send/[collectionId].vue
- pages/nft-book-store/collection/send/shipping/[collectionId].vue
- pages/nft-book-store/collection/status/[collectionId].vue
- pages/nft-book-store/send/[classId].vue
- pages/nft-book-store/send/shipping/[classId].vue
- pages/nft-book-store/status/[classId].vue
- utils/cosmos.ts
https://github.com/likecoin/likecoin-api-public/pull/699
> [TAS-1847] ✨ Support book quantity

- pages/nft-book-store/status/[classId].vue
> 🐛 Fix order index is used as price index

- pages/nft-book-store/collection/send/shipping/[collectionId].vue
- pages/nft-book-store/send/shipping/[classId].vue
Fix https://github.com/likecoin/nft-book-press/issues/161
> 🚸 Disable ship button for shipped order

- stores/stripe.ts
Add token to `fetchStripeConnectStatus`
> 🐛 Fix missing stripe email

- app.vue
- components/WalletHeader.vue
- pages/auth/redirect.vue
- pages/nft-book-store.vue
https://github.com/user-attachments/assets/7403a365-9c98-492b-ba93-0a93434f82dd
> 🐛 Fix missing signer issue during redirect for AuthCore

- pages/nft-book-store/collection/new.vue
- pages/nft-book-store/collection/status/[collectionId]/edit.vue
- pages/nft-book-store/new.vue
- pages/nft-book-store/status/[classId]/edit/[editionIndex].vue
- pages/nft-book-store/status/[classId]/edit/new.vue
- utils/cosmos.ts
Require: https://github.com/likecoin/likecoin-api-public/pull/717
> [TAS-958] ✨ Support auto deliver for collection

- pages/nft-book-store/collection/status/[collectionId].vue
- pages/nft-book-store/status/[classId].vue
> [TAS-2069] 🐛 Fix missing coupon field for purchase link

- pages/nft-book-store/user/index.vue
When the Liker Id is initially set up, the API sometime does not return the id information immediately
> 🎨 Add ts query to getUserMin API to prevent caching

- pages/nft-book-store/user/index.vue
- stores/user.ts
> [TAS-2159] 💄 Clean up notification email settings UI

- pages/affiliation-link.vue
> 🚸 Rename product ID field in affiliation link

- pages/nft-book-store/status/[classId]/edit/[editionIndex].vue
Fixes [NFT-BOOK-PRESS-F](https://likerland-team.sentry.io/issues/5873668938/)
> 🐛 Fix undefined function

- components/StripeConnectCard.vue
- constant/index.ts
- pages/affiliation-link.vue
- pages/nft-book-store/collection/new.vue
- pages/nft-book-store/collection/status/[collectionId].vue
- pages/nft-book-store/new.vue
- pages/nft-book-store/status/[classId].vue
- pages/nft-book-store/user/index.vue
- stores/liker.ts
- stores/static-data.ts
- stores/stripe.ts
- stores/user.ts
- utils/api.ts
- utils/index.ts
> [TAS-2199] 🚸 Improve affiliation link UX

- components/SiteMenu.vue
- pages/affiliation-link.vue
- pages/batch-short-links.vue
- pages/nft-book-store/status/[classId].vue
> [TAS-2297] ✨ Support short link with Short.io

- components/QRCodeGenerator.vue
- components/SiteMenu.vue
- package.json
- pages/nft-book-store.vue
- pages/nft-book-store/user/index.vue
- pages/sales-pos/index.vue
- stores/nft.ts
- yarn.lock
> [TAS-2203] ✨ Add bookstore pos page

- pages/affiliation-link.vue
- utils/index.ts
> [TAS-2318] 🚸 Make product ID optional when using custom link

- pages/sales-pos/index.vue
> [TAS-2346] 💄 Improve POS UI for coupon

- components/PageHeader.vue
- layouts/default.vue
- pages/affiliation-link.vue
- utils/app.ts
> [TAS-2333] ✨ Support multiple products in affiliation link

- composables/useMessageCharCount.ts
- constant/index.ts
- pages/nft-book-store/collection/send/[collectionId].vue
- pages/nft-book-store/send/[classId].vue
> [TAS-1863] ✨ Add character count limit for author's message

- pages/nft-book-store/collection/new.vue
- pages/nft-book-store/collection/status/[collectionId]/edit.vue
- pages/nft-book-store/new.vue
- pages/nft-book-store/status/[classId]/edit/[editionIndex].vue
- pages/nft-book-store/status/[classId]/edit/new.vue
Requires: https://github.com/likecoin/likecoin-api-public/pull/803
> [TAS-2313] ✨ Add isUnlisted for prices

- components/AuthStateView.vue
- utils/index.ts
> [TAS-2009] ✨ Add address copy feature

- pages/affiliation-link.vue
> [TAS-2538] ✨ Improve affiliation link for sharing

- app.vue
> 🐛 Fix favicon

- pages/affiliation-link.vue
> [TAS-2538] ✨ Add share table button & fix issues

- components/SiteMenu.vue
- pages/index.vue
- pages/latest-books.vue
- pages/nft-book-store/books.vue
> [TAS-1162] ✨ Add latest book list for affiliate

- pages/mint-nft/index.vue
> 🚸 Add guide banner in mint nft page

- components/SiteMenu.vue
> 💄 Refactor menu items

- nuxt.config.ts
- package.json
- pages/nft-book-store/collection/send/[collectionId].vue
- pages/nft-book-store/collection/send/shipping/[collectionId].vue
- pages/nft-book-store/send/[classId].vue
- pages/nft-book-store/send/shipping/[classId].vue
- plugins/buffer.ts
- stores/book-store-api.ts
- yarn.lock
Replaced/Upgraded node modules to allow simpler polyfill
Uses nuxt builtin unenv instead of vite plugin for polyfill
> ⬆️ Upgrade nuxt to 3.12

- nuxt.config.ts
- package.json
- pages/nft-book-store/collection/send/[collectionId].vue
- pages/nft-book-store/collection/send/shipping/[collectionId].vue
- pages/nft-book-store/send/[classId].vue
- pages/nft-book-store/send/shipping/[classId].vue
- plugins/buffer.ts
- stores/book-store-api.ts
- yarn.lock
COEP & COOP would affect authcore login
sentry replay utlize `worker-src`
> ⬆️ Upgrade nuxt to 3.13 & 🔒️ Update security rule for sentry and authcore

- package.json
- yarn.lock
Ref: https://github.com/nuxt/ui/issues/1685
> ⬆️ Upgrade @nuxt/ui to fix tailwind build log spam

- components/AuthRequiredView.vue
- components/AuthStateView.vue
- composables/useAuth.ts
- pages/latest-books.vue
> [TAS-2797]📱 Add sign in button for mobile

- .env
- .env.production
- nuxt.config.ts
- package.json
- yarn.lock
Requires https://github.com/likecoin/nft-book-press/pull/237
> [TAS-2162] ⬆️ Add nuxt script and crisp

- pages/latest-books.vue
> [TAS-2822] ✨ Add best sellers tab

- pages/batch-qrcode.vue
- pages/batch-short-links.vue
- pages/mint-nft/index.vue
- pages/nft-book-store/gift/[classId].vue
> 👽️ Fix file @change handler interface changes

- components/ShippingRates/RateTable.vue
- components/StripeConnectCard.vue
- pages/mint-nft/index.vue
- pages/nft-book-store/collection/new.vue
- pages/nft-book-store/collection/status/[collectionId].vue
- pages/nft-book-store/collection/status/[collectionId]/edit.vue
- pages/nft-book-store/new.vue
- pages/nft-book-store/status/[classId].vue
- pages/nft-book-store/status/[classId]/edit/[editionIndex].vue
- pages/nft-book-store/status/[classId]/edit/new.vue
> [TAS-3027] 🌐 Add Chinese language support for labels

- pages/nft-book-store/collection/status/[collectionId].vue
- pages/nft-book-store/status/[classId].vue
Require: https://github.com/likecoin/likecoin-api-public/pull/848
> [TAS-3102] ✨ Add send reminder email in order action

- pages/nft-book-store/collection/status/[collectionId].vue
- pages/nft-book-store/status/[classId].vue
Fixes https://github.com/likecoin/nft-book-press/issues/267
> 🚸 Fix pendingNFT count should not change if status not match

- app.vue
- components/SiteMenu.vue
- composables/useAuth.ts
- pages/nft-book-store/collection/status/[collectionId].vue
- pages/nft-book-store/index.vue
- pages/nft-book-store/status/[classId].vue
- stores/book-store-api.ts
- stores/collection.ts
Fixes https://github.com/likecoin/nft-book-press/issues/257
> [TAS-3162] 🚸 Add listing unhandled count badge in side menu

- pages/latest-books.vue
> [TAS-2750] ✨ Add search filter in latest books table

- pages/nft-book-store/collection/status/[collectionId].vue
- pages/nft-book-store/status/[classId].vue
> [TAS-3353] 🚸 Display pending shipping in status list

- pages/batch-short-links.vue
- pages/latest-books.vue
- pages/mint-nft/index.vue
- pages/nft-book-store/collection/index.vue
- pages/nft-book-store/collection/new.vue
- pages/nft-book-store/collection/send/[collectionId].vue
- pages/nft-book-store/collection/send/shipping/[collectionId].vue
- pages/nft-book-store/collection/status/[collectionId].vue
- pages/nft-book-store/collection/status/[collectionId]/edit.vue
- pages/nft-book-store/gift/[classId].vue
- pages/nft-book-store/new.vue
- pages/nft-book-store/send/[classId].vue
- pages/nft-book-store/send/shipping/[classId].vue
- pages/nft-book-store/status/[classId].vue
- pages/nft-book-store/status/[classId]/edit/[editionIndex].vue
- pages/nft-book-store/status/[classId]/edit/new.vue
- pages/nft-book-store/user/connect/return.vue
- pages/nft-book-store/user/index.vue
- pages/nft-book-store/user/payouts/[payoutId].vue
- pages/purchase-link.vue
- pages/sales-pos/index.vue
- stores/book-store-api.ts
- stores/collection.ts
- stores/liker.ts
- stores/nft.ts
- stores/stripe.ts
- stores/user.ts
- utils/api.ts
- utils/arweave.ts
https://www.youtube.com/watch?v=njsGVmcWviY
useFetch should be used in composable or top level, when we want a change in data auto trigger a fetch
> ♻️ Use $fetch instead of useFetch

- utils/cosmos.ts
- utils/iscn.ts
[[TAS-3523] merge iscn signing client and cosmos signing client in book press](https://www.notion.so/likecoin/merge-iscn-signing-client-and-cosmos-signing-client-in-book-press-1c26658c4c68807680c3ed585d5c395c?pvs=4)
[[TAS-3524] lazy load cosmos-js and iscn-js in bookpress](https://www.notion.so/likecoin/lazy-load-cosmos-js-and-iscn-js-in-bookpress-1c26658c4c68809ea09cce4db0acc3c3?pvs=4)
> [TAS-3524] ⚡️ Lazy load iscn-js and cosmos-js related imports

- components/ISCNInfoCard.vue
- components/MintNFT.vue
- components/NFTMintForm.vue
- components/NewNFTBook.vue
- components/RegisterISCN.vue
- pages/mint-nft/index.vue
- pages/nft-book-store/collection/status/[collectionId]/edit.vue
- pages/publish-nft-book/index.vue
- stores/upload.ts
> ✨ Simplify Minting flow

- components/NewNFTBook.vue
- pages/nft-book-store/collection/index.vue
- pages/nft-book-store/index.vue
- pages/nft-book-store/status/[classId].vue
> [TAS-3432] 🐛 Fix restocking issues

- components/EditISCNMetadataModal.vue
- components/ISCNForm.vue
- components/LiteMintNFT.vue
- components/NFTMintForm.vue
- components/RegisterISCN.vue
- composables/useToast.ts
- pages/publish-nft-book/index.vue
> 🚸 Display form errors instead of disabling the submit button

- components/EditISCNMetadataModal.vue
- components/ISCNForm.vue
- components/LiteMintNFT.vue
- components/RegisterISCN.vue
- utils/iscn.ts
> [TAS-3873] 🔈 Display specific field where the error occurred

- components/UploadForm.vue
Make `setEbookCoverFromImages` add `thumbnailArweaveId` to the existing cover object, instead of pushing a new one.
> [TAS-4036] 🐛 Set thumbnailArweaveId without adding new entry to epubMetadataList

- pages/nft-book-store/collection/status/[collectionId].vue
- pages/nft-book-store/status/[classId].vue
- pages/nft-book-store/user/index.vue
Also pages are missing i18n, will PR later
> 🐛 Fix missing localeRoute

- .env
- app.vue
- components/MaintenancePage.vue
- composables/useMaintenanceMode.ts
- composables/useRouteQuery.ts
- i18n/locales/en.json
- i18n/locales/zh-TW.json
- middleware/query.global.ts
- nuxt.config.ts
> [TAS-4656] ✨ Add maintenance page
